import {
  User,
  FileText,
  Wrench,
  DollarSign,
  Archive,
  Calendar,
  BookOpen,
  UserPlus,
  Home,
  Leaf,
  Lightbulb,
  Package,
  Clock,
  TrendingUp,
  Shield,
  Lock,
} from "lucide-react";
import { HomePageList } from "./Types";
import { useMemo } from "react";


export default function MenuItens() {
    const menuItems: HomePageList[] = useMemo(
    () => [
      {
        id: 1,
        title: "Meus Dados",
        description:
          "Atualize suas informações pessoais, endereço e preferências de contato",
        icon: User,
        color: "bg-gradient-to-br from-gray-600 to-gray-700",
        link: "/meus-dados",
        tags: ["perfil", "dados", "contato", "limite de crédito"],
        admin: false,
        unlocked: true,
      },
      {
        id: 2,
        title: "Orçamentos",
        description: "Visualize e aprove orçamentos digitalmente",
        icon: FileText,
        color: "bg-gradient-to-br from-orange-500 to-orange-600",
        link: "/orcamentos",
        tags: ["orçamento", "aprovação", "proposta", "valores"],
        admin: false,
        unlocked: true,
      },
      {
        id: 3,
        title: "Acompanhamento do Projeto",
        description: "Veja a evolução do seu projeto em tempo real",
        icon: TrendingUp,
        color: "bg-gradient-to-br from-gray-500 to-gray-600",
        link: "/projeto",
        tags: ["timeline", "produção", "status", "etapas"],
        admin: false,
        unlocked: true,
      },
      {
        id: 4,
        title: "SAC - Atendimento",
        description: "Abra chamados e acompanhe o suporte técnico",
        icon: Wrench,
        color: "bg-orange-500",
        link: "/sac",
        tags: ["suporte", "chamados", "atendimento", "problemas"],
        admin: false,
        unlocked: true,
      },
      {
        id: 5,
        title: "Documentos",
        description: "Consulte duplicatas, boletos, extratos, contratos, plantas e mais",
        icon: Archive,
        color: "bg-emerald-500",
        link: "/financeiro",
        tags: ["boletos", "pagamentos", "duplicatas", "pix"],
        admin: false,
        unlocked: true,
      },
      {
        id: 6,
        title: "Linha do Tempo",
        description: "Histórico completo de todas as interações",
        icon: Clock,
        color: "bg-pink-500",
        link: "/timeline",
        tags: ["histórico", "feed", "atividades", "interações"],
        admin: false,
        unlocked: false,
      },

      // 🔒 Em construção (exemplos)
      {
        id: 7,
        title: "Assinaturas Digitais",
        description: "Assine documentos eletronicamente com Clicksign",
        icon: FileText,
        color: "bg-red-500",
        link: "/assinaturas",
        tags: ["assinatura", "clicksign", "documentos"],
        admin: false,
        unlocked: false,
      },
      {
        id: 8,
        title: "Agenda de Visitas",
        description: "Solicite e acompanhe visitas técnicas",
        icon: Calendar,
        color: "bg-cyan-500",
        link: "/visitas",
        tags: ["visita", "agendamento", "técnica", "assessoria"],
        admin: false,
        unlocked: false,
      },

      {
        id: 9,
        title: "Academia Smart",
        description: "Conteúdos educativos sobre construção e steel frame",
        icon: BookOpen,
        color: "bg-yellow-500",
        link: "/academia",
        tags: ["vídeos", "guias", "cases", "dicas"],
        admin: false,
        unlocked: false,
      },
      {
        id: 10,
        title: "Indicações",
        description: "Indique amigos e ganhe recompensas",
        icon: UserPlus,
        color: "bg-teal-500",
        link: "/indicacoes",
        tags: ["indicar", "recompensas", "programa", "amigos"],
        admin: false,
        unlocked: false,
      },
      {
        id: 11,
        title: "Minha Casa Digital",
        description: "Visualize detalhes técnicos e materiais da sua obra",
        icon: Home,
        color: "bg-violet-500",
        link: "/casa-digital",
        tags: ["materiais", "aço", "plantas 3d", "qr code"],
        admin: false,
        unlocked: false,
      },
      {
        id: 12,
        title: "Memorial de Materiais",
        description: "Lista completa de materiais utilizados no projeto",
        icon: Package,
        color: "bg-slate-500",
        link: "/memorial-materiais",
        tags: ["materiais", "lista", "especificações"],
        admin: false,
        unlocked: false,
      },
      {
        id: 13,
        title: "Sustentabilidade",
        description: "Acompanhe o impacto sustentável do seu projeto",
        icon: Leaf,
        color: "bg-lime-500",
        link: "/sustentabilidade",
        tags: ["sustentômetro", "economia", "verde", "impacto"],
        admin: false,
        unlocked: false,
      },
      {
        id: 14,
        title: "Dicas Smart",
        description: "Sugestões personalizadas para complementar seu projeto",
        icon: Lightbulb,
        color: "bg-amber-500",
        link: "/dicas",
        tags: ["upsell", "sugestões", "esquadrias", "complementos"],
        admin: false,
        unlocked: false,
      },

      // ADMIN
      {
        id: 15,
        title: "Administração",
        description: "Área exclusiva para administradores do sistema",
        icon: Shield,
        color: "bg-black",
        link: "/admin",
        tags: ["admin", "gestão", "sistema", "controle"],
        admin: true,
        unlocked: true,
      },
    ],
    []
  );
    return menuItems;
}